export const reservoirAddress = "0xeEc83a83764c41f9c602694dfCffC9E75A8Ef3B6";
export const reservoirAbi = [{
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "dividendsOf",
    "inputs": [{
        "type": "address",
        "name": "_customerAddress"
    }],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "lockedTokenBalance",
    "inputs": [],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "uint256[15]",
        "name": ""
    }],
    "name": "statsOf",
    "inputs": [{
        "type": "address",
        "name": "_customerAddress"
    }],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "totalSupply",
    "inputs": [],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "myDividends",
    "inputs": [],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "dividendBalance",
    "inputs": [],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "nonpayable",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "sweep",
    "inputs": [],
    "constant": false
}, {
    "type": "function",
    "stateMutability": "nonpayable",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "withdraw",
    "inputs": [],
    "constant": false
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "totalTokenBalance",
    "inputs": [],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "totalClaims",
    "inputs": [],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "calculateTaxedBnbToTokenLiquidity",
    "inputs": [{
        "type": "uint256",
        "name": "_amount"
    }],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "calculateTaxedLiquidityToBnb",
    "inputs": [{
        "type": "uint256",
        "name": "_amount"
    }],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "address",
        "name": ""
    }],
    "name": "collateralAddress",
    "inputs": [],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "totalWithdrawn",
    "inputs": [],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "totalTxs",
    "inputs": [],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "calculateLiquidityToBnb",
    "inputs": [{
        "type": "uint256",
        "name": "_amount"
    }],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "balanceOf",
    "inputs": [{
        "type": "address",
        "name": "_customerAddress"
    }],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "distributionInterval",
    "inputs": [],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "totalDeposits",
    "inputs": [],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "address",
        "name": ""
    }],
    "name": "swapAddress",
    "inputs": [],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "myTokens",
    "inputs": [],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "dailyEstimateBnb",
    "inputs": [{
        "type": "address",
        "name": "_customerAddress"
    }],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "payable",
    "payable": true,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "buy",
    "inputs": [],
    "constant": false
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "lastPayout",
    "inputs": [],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "collateralBalance",
    "inputs": [],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "bnbBalance",
    "inputs": [{
        "type": "address",
        "name": "_customerAddress"
    }],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "players",
    "inputs": [],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "nonpayable",
    "payable": false,
    "outputs": [],
    "name": "sell",
    "inputs": [{
        "type": "uint256",
        "name": "_amountOfTokens"
    }],
    "constant": false
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "dailyEstimate",
    "inputs": [{
        "type": "address",
        "name": "_customerAddress"
    }],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "view",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "balanceInterval",
    "inputs": [],
    "constant": true
}, {
    "type": "function",
    "stateMutability": "nonpayable",
    "payable": false,
    "outputs": [{
        "type": "uint256",
        "name": ""
    }],
    "name": "reinvest",
    "inputs": [],
    "constant": false
}, {
    "type": "constructor",
    "stateMutability": "nonpayable",
    "payable": false,
    "inputs": [{
        "type": "address",
        "name": "_swapAddress"
    }, {
        "type": "address",
        "name": "_collateralAddress"
    }]
}, {
    "type": "fallback",
    "stateMutability": "payable",
    "payable": true
}, {
    "type": "event",
    "name": "onLeaderBoard",
    "inputs": [{
        "type": "address",
        "name": "customerAddress",
        "indexed": true
    }, {
        "type": "uint256",
        "name": "invested",
        "indexed": false
    }, {
        "type": "uint256",
        "name": "tokens",
        "indexed": false
    }, {
        "type": "uint256",
        "name": "soldTokens",
        "indexed": false
    }, {
        "type": "uint256",
        "name": "timestamp",
        "indexed": false
    }],
    "anonymous": false
}, {
    "type": "event",
    "name": "onTokenPurchase",
    "inputs": [{
        "type": "address",
        "name": "customerAddress",
        "indexed": true
    }, {
        "type": "uint256",
        "name": "incomingeth",
        "indexed": false
    }, {
        "type": "uint256",
        "name": "tokensMinted",
        "indexed": false
    }, {
        "type": "uint256",
        "name": "timestamp",
        "indexed": false
    }],
    "anonymous": false
}, {
    "type": "event",
    "name": "onTokenSell",
    "inputs": [{
        "type": "address",
        "name": "customerAddress",
        "indexed": true
    }, {
        "type": "uint256",
        "name": "tokensBurned",
        "indexed": false
    }, {
        "type": "uint256",
        "name": "ethEarned",
        "indexed": false
    }, {
        "type": "uint256",
        "name": "timestamp",
        "indexed": false
    }],
    "anonymous": false
}, {
    "type": "event",
    "name": "onReinvestment",
    "inputs": [{
        "type": "address",
        "name": "customerAddress",
        "indexed": true
    }, {
        "type": "uint256",
        "name": "ethReinvested",
        "indexed": false
    }, {
        "type": "uint256",
        "name": "tokensMinted",
        "indexed": false
    }, {
        "type": "uint256",
        "name": "timestamp",
        "indexed": false
    }],
    "anonymous": false
}, {
    "type": "event",
    "name": "onWithdraw",
    "inputs": [{
        "type": "address",
        "name": "customerAddress",
        "indexed": true
    }, {
        "type": "uint256",
        "name": "ethWithdrawn",
        "indexed": false
    }, {
        "type": "uint256",
        "name": "timestamp",
        "indexed": false
    }],
    "anonymous": false
}, {
    "type": "event",
    "name": "onClaim",
    "inputs": [{
        "type": "address",
        "name": "customerAddress",
        "indexed": true
    }, {
        "type": "uint256",
        "name": "tokens",
        "indexed": false
    }, {
        "type": "uint256",
        "name": "timestamp",
        "indexed": false
    }],
    "anonymous": false
}, {
    "type": "event",
    "name": "onTransfer",
    "inputs": [{
        "type": "address",
        "name": "from",
        "indexed": true
    }, {
        "type": "address",
        "name": "to",
        "indexed": true
    }, {
        "type": "uint256",
        "name": "tokens",
        "indexed": false
    }, {
        "type": "uint256",
        "name": "timestamp",
        "indexed": false
    }],
    "anonymous": false
}, {
    "type": "event",
    "name": "onBalance",
    "inputs": [{
        "type": "uint256",
        "name": "bnbBalance",
        "indexed": false
    }, {
        "type": "uint256",
        "name": "tokenBalance",
        "indexed": false
    }, {
        "type": "uint256",
        "name": "timestamp",
        "indexed": false
    }],
    "anonymous": false
}, {
    "type": "event",
    "name": "onLiquiditySweep",
    "inputs": [{
        "type": "uint256",
        "name": "amount",
        "indexed": false
    }],
    "anonymous": false
}, {
    "type": "event",
    "name": "onLiquidityProviderReward",
    "inputs": [{
        "type": "uint256",
        "name": "amount",
        "indexed": false
    }],
    "anonymous": false
}]